#line 2 "vhdl_flex.c"

#line 4 "vhdl_flex.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 6
#define YY_FLEX_SUBMINOR_VERSION 0
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

#ifdef __cplusplus

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

/* C99 requires __STDC__ to be defined as 1. */
#if defined (__STDC__)

#define YY_USE_CONST

#endif	/* defined (__STDC__) */
#endif	/* ! __cplusplus */

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* An opaque pointer. */
#ifndef YY_TYPEDEF_YY_SCANNER_T
#define YY_TYPEDEF_YY_SCANNER_T
typedef void* yyscan_t;
#endif

/* For convenience, these vars (plus the bison vars far below)
   are macros in the reentrant scanner. */
#define yyin yyg->yyin_r
#define yyout yyg->yyout_r
#define yyextra yyg->yyextra_r
#define yyleng yyg->yyleng_r
#define yytext yyg->yytext_r
#define yylineno (YY_CURRENT_BUFFER_LVALUE->yy_bs_lineno)
#define yycolumn (YY_CURRENT_BUFFER_LVALUE->yy_bs_column)
#define yy_flex_debug yyg->yy_flex_debug_r

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN yyg->yy_start = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START ((yyg->yy_start - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE urj_vhdl_restart(yyin ,yyscanner )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

    #define YY_LESS_LINENO(n)
    #define YY_LINENO_REWIND_TO(ptr)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = yyg->yy_hold_char; \
		YY_RESTORE_YY_MORE_OFFSET \
		yyg->yy_c_buf_p = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, yyg->yytext_ptr , yyscanner )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */
    
	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via urj_vhdl_restart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( yyg->yy_buffer_stack \
                          ? yyg->yy_buffer_stack[yyg->yy_buffer_stack_top] \
                          : NULL)

/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE yyg->yy_buffer_stack[yyg->yy_buffer_stack_top]

void urj_vhdl_restart (FILE *input_file ,yyscan_t yyscanner );
void urj_vhdl__switch_to_buffer (YY_BUFFER_STATE new_buffer ,yyscan_t yyscanner );
YY_BUFFER_STATE urj_vhdl__create_buffer (FILE *file,int size ,yyscan_t yyscanner );
void urj_vhdl__delete_buffer (YY_BUFFER_STATE b ,yyscan_t yyscanner );
void urj_vhdl__flush_buffer (YY_BUFFER_STATE b ,yyscan_t yyscanner );
void urj_vhdl_push_buffer_state (YY_BUFFER_STATE new_buffer ,yyscan_t yyscanner );
void urj_vhdl_pop_buffer_state (yyscan_t yyscanner );

static void urj_vhdl_ensure_buffer_stack (yyscan_t yyscanner );
static void urj_vhdl__load_buffer_state (yyscan_t yyscanner );
static void urj_vhdl__init_buffer (YY_BUFFER_STATE b,FILE *file ,yyscan_t yyscanner );

#define YY_FLUSH_BUFFER urj_vhdl__flush_buffer(YY_CURRENT_BUFFER ,yyscanner)

YY_BUFFER_STATE urj_vhdl__scan_buffer (char *base,yy_size_t size ,yyscan_t yyscanner );
YY_BUFFER_STATE urj_vhdl__scan_string (yyconst char *yy_str ,yyscan_t yyscanner );
YY_BUFFER_STATE urj_vhdl__scan_bytes (yyconst char *bytes,yy_size_t len ,yyscan_t yyscanner );

void *urj_vhdl_alloc (yy_size_t ,yyscan_t yyscanner );
void *urj_vhdl_realloc (void *,yy_size_t ,yyscan_t yyscanner );
void urj_vhdl_free (void * ,yyscan_t yyscanner );

#define yy_new_buffer urj_vhdl__create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        urj_vhdl_ensure_buffer_stack (yyscanner); \
		YY_CURRENT_BUFFER_LVALUE =    \
            urj_vhdl__create_buffer(yyin,YY_BUF_SIZE ,yyscanner); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        urj_vhdl_ensure_buffer_stack (yyscanner); \
		YY_CURRENT_BUFFER_LVALUE =    \
            urj_vhdl__create_buffer(yyin,YY_BUF_SIZE ,yyscanner); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */

typedef unsigned char YY_CHAR;

typedef int yy_state_type;

#define yytext_ptr yytext_r

static yy_state_type yy_get_previous_state (yyscan_t yyscanner );
static yy_state_type yy_try_NUL_trans (yy_state_type current_state  ,yyscan_t yyscanner);
static int yy_get_next_buffer (yyscan_t yyscanner );
#if defined(__GNUC__) && __GNUC__ >= 3
__attribute__((__noreturn__))
#endif
static void yy_fatal_error (yyconst char msg[] ,yyscan_t yyscanner );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	yyg->yytext_ptr = yy_bp; \
	yyleng = (size_t) (yy_cp - yy_bp); \
	yyg->yy_hold_char = *yy_cp; \
	*yy_cp = '\0'; \
	yyg->yy_c_buf_p = yy_cp;

#define YY_NUM_RULES 82
#define YY_END_OF_BUFFER 83
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static yyconst flex_int16_t yy_acclist[463] =
    {   0,
       72,   72,   72,   72,   72,   72,   72,   72,   72,   72,
       83,   81,   82,   72,   82,   63,   82,   82,   79,   82,
       70,   82,   65,   82,   66,   82,   82,   64,   82,   81,
       82,   67,   82,   74,   77,   82,   77,   82,   68,   82,
       80,   82,   82,   75,   82,   75,   82,   75,   82,   75,
       82,   75,   82,   75,   82,   75,   82,   75,   82,   75,
       82,   75,   82,   75,   82,   75,   82,   75,   82,   75,
       82,   75,   82,   75,   82,   74,   75,   82,   75,   82,
       75,   82,   75,   82,   75,   82,   62,   75,   82,   75,
       82,   75,   82,   75,   82,   75,   82,   75,   82,   75,

       82,   75,   82,   75,   82,   75,   82,   59,   74,   75,
       82,   75,   82,   72,   76,   73,   74,   77,   77,   74,
       71,   69,   75,   75,   75,   75,   75,   75,   75,   75,
       75,   75,   75,   75,   75,   75,   19,   75,    6,   75,
       75,   75,   11,   75,   75,   75,   75,   75,   75,   75,
       75,   75,   75,   75,   26,   75,   75,   75,   75,   74,
       75,   75,   75,   75,   19,   75,   75,   75,   75,   75,
       75,   19,   75,   75,   55,   75,   56,   75,   75,   75,
       75,   75,   73,   10,   75,   75,   75,   24,   75,   75,
       75,   75,   75,   75,   75,   75,    9,   75,   75,   75,

       75,   75,   75,   17,   75,   20,   75,   75,   75,   75,
       75,   75,   75,   75,   75,   75,   75,   75,   75,   75,
        4,   75,   75,   75,   75,   75,   75,   75,   20,   75,
       75,   58,   75,   75,   75,   61,   75,   75,   75,   57,
       75,   75,   75,   75,   75,   29,   75,   18,   75,   75,
       75,   75,   75,   75,   75,   75,   75,   75,   75,   75,
       75,   75,    2,   75,   75,   75,   75,   75,   75,   75,
       75,   14,   75,   30,   75,   75,   75,   75,   75,   75,
       75,   75,   75,   75,   75,   75,   75,   60,   75,   78,
       33,   75,   75,   75,   75,   75,   75,   75,   75,   75,

       15,   75,   75,   21,   75,   75,   75,   75,   75,   75,
       35,   75,   75,   75,   75,   75,   75,   48,   75,   46,
       75,   75,   40,   75,   75,   75,   75,   75,   75,   75,
       75,   75,   75,   75,   75,   22,   75,   75,   75,   27,
       75,    1,   75,   75,   75,   75,   75,   75,   75,   32,
       75,   16,   75,   75,    8,   75,   75,   75,   75,   75,
       75,   75,   51,   75,   53,   75,   75,   52,   75,   75,
       75,   75,   75,   75,    3,   75,   23,   75,   28,   75,
       75,   75,   75,   75,   31,   75,   44,   75,   75,   75,
       41,   75,   42,   75,   75,   75,   54,   75,   75,   75,

       75,   75,    7,   75,   75,   75,   34,   75,   75,   43,
       75,   45,   75,   75,   49,   75,   75,    5,   75,   75,
       75,   36,   75,   75,   75,   75,   75,   50,   75,   25,
       75,   75,   75,   75,   75,   75,   75,   75,   75,   75,
       75,   75,   75,   75,   75,   47,   75,   75,   75,   75,
       38,   75,   39,   75,   37,   75,   75,   13,   75,   75,
       12,   75
    } ;

static yyconst flex_int16_t yy_accept[353] =
    {   0,
        1,    2,    3,    4,    5,    6,    7,    8,    9,   10,
       11,   12,   14,   16,   18,   19,   21,   23,   25,   27,
       28,   30,   32,   34,   37,   39,   41,   43,   44,   46,
       48,   50,   52,   54,   56,   58,   60,   62,   64,   66,
       68,   70,   72,   74,   76,   79,   81,   83,   85,   87,
       90,   92,   94,   96,   98,  100,  102,  104,  106,  108,
      112,  114,  115,  115,  116,  117,  117,  119,  120,  121,
      122,  123,  124,  125,  126,  127,  128,  129,  130,  131,
      132,  133,  134,  135,  136,  137,  139,  141,  142,  143,
      145,  146,  147,  148,  149,  150,  151,  152,  153,  154,

      155,  157,  158,  159,  160,  162,  163,  164,  165,  167,
      168,  169,  170,  171,  172,  174,  175,  177,  179,  180,
      181,  182,  183,  184,  184,  186,  187,  188,  190,  191,
      192,  193,  194,  195,  196,  197,  199,  200,  201,  202,
      203,  204,  206,  208,  209,  210,  211,  212,  213,  214,
      215,  216,  217,  218,  219,  220,  221,  223,  224,  225,
      226,  227,  228,  229,  231,  232,  234,  235,  236,  238,
      239,  240,  242,  243,  243,  244,  245,  246,  248,  250,
      251,  252,  253,  254,  255,  256,  257,  258,  259,  260,
      261,  262,  263,  265,  266,  267,  268,  269,  270,  271,

      272,  274,  276,  277,  278,  279,  280,  281,  282,  283,
      284,  285,  286,  287,  288,  290,  290,  291,  293,  294,
      295,  296,  297,  298,  299,  300,  301,  303,  304,  306,
      307,  308,  309,  310,  311,  313,  314,  315,  316,  317,
      318,  320,  322,  323,  325,  326,  327,  328,  329,  330,
      331,  332,  333,  334,  335,  336,  338,  339,  340,  342,
      344,  345,  346,  347,  348,  349,  350,  352,  354,  355,
      357,  358,  359,  360,  361,  362,  363,  365,  367,  368,
      370,  371,  372,  373,  374,  375,  377,  379,  381,  382,
      383,  384,  385,  387,  389,  390,  391,  393,  395,  396,

      397,  399,  400,  401,  402,  403,  405,  406,  407,  409,
      410,  412,  414,  415,  417,  418,  420,  421,  422,  424,
      425,  426,  427,  428,  430,  432,  433,  434,  435,  436,
      437,  438,  439,  440,  441,  442,  443,  444,  445,  446,
      448,  449,  450,  451,  453,  455,  457,  458,  460,  461,
      463,  463
    } ;

static yyconst YY_CHAR yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    2,    2,    3,
        1,    1,    2,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    1,    4,    1,    1,    1,    5,    6,    7,
        8,    9,   10,   11,   12,   13,    1,   14,   15,   16,
       17,   18,   19,   18,   18,   18,   18,   20,   21,   22,
       23,   24,    1,    1,   25,   26,   27,   28,   29,   30,
       31,   32,   33,   34,   35,   36,   37,   38,   39,   40,
       34,   41,   42,   43,   44,   45,   46,   47,   48,   49,
        9,    1,    9,    1,   50,    1,   51,   52,   53,   54,

       55,   56,   57,   58,   59,   34,   60,   61,   62,   63,
       64,   65,   34,   66,   67,   68,   69,   70,   71,   72,
       73,   74,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst YY_CHAR yy_meta[75] =
    {   0,
        1,    1,    2,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    3,    3,    3,    3,    3,    3,    1,
        1,    1,    1,    1,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3
    } ;

static yyconst flex_uint16_t yy_base[355] =
    {   0,
        0,    0,    0,    0,   49,   51,    0,    0,  100,    0,
      522,  823,  489,  823,  475,  823,  823,  823,  823,  823,
      823,  414,  823,  103,   78,  385,  823,  353,   95,  118,
       50,   42,   48,   58,   99,    0,  138,  140,  102,  156,
      161,  150,  169,   45,  177,  188,  167,  187,  214,    0,
      204,  236,  213,  236,  254,  256,  257,  286,  103,  310,
      168,  362,  318,  823,    0,  317,  325,  333,  313,  823,
      823,    0,   63,  170,  170,  191,  236,  172,  211,  233,
      239,  247,  325,  260,  318,  319,    0,  321,  315,    0,
      319,  336,  317,  328,  328,  329,  346,  343,  347,  350,

        0,  327,  338,  351,  390,  379,  359,  371,  371,  373,
      373,  384,  377,  375,  381,  396,  381,  387,  392,  394,
      404,  407,    0,  449,    0,  425,  416,  266,  411,  428,
      433,  431,  434,  429,  434,    0,  441,  435,  446,  436,
      446,    0,    0,  448,  443,  263,  445,  456,  459,  453,
      455,  259,  465,  460,  470,  478,    0,  476,  484,  477,
      470,  483,  492,  483,  493,    0,  498,  500,    0,  504,
      492,    0,  495,  548,  488,  509,  501,    0,    0,  255,
      514,  212,  506,  507,  508,  525,  529,  529,  548,  552,
      545,  544,    0,  539,  550,  542,  559,  241,  548,  539,

        0,    0,  547,  554,  549,  548,  551,  552,  550,  555,
      556,  559,  569,  573,    0,  621,  627,    0,  596,  595,
      598,  588,  597,  606,  594,  599,    0,  616,    0,  620,
      621,  628,  634,  627,    0,  633,  627,  234,  633,  626,
        0,    0,  628,    0,  630,  624,  627,  195,  628,  630,
      632,  647,  635,  653,  635,    0,  645,  646,    0,    0,
      662,  668,  671,  676,  663,  660,    0,    0,  222,    0,
      681,  676,  688,  685,  118,  683,    0,    0,  675,    0,
      676,  677,  678,  694,  686,    0,    0,    0,  695,  152,
      696,  182,    0,  691,  697,  134,    0,    0,  696,  691,

        0,  709,  702,  719,  713,    0,  128,  711,    0,   98,
        0,    0,  716,    0,  718,    0,  721,  725,    0,  725,
      724,  121,  730,    0,    0,  727,  716,  729,  116,  735,
      739,  738,  740,   93,  731,  742,   35,  744,  525,    0,
      745,  747,  754,    0,    0,    0,  764,    0,  751,    0,
      823,  816,   77,  819
    } ;

static yyconst flex_int16_t yy_def[355] =
    {   0,
      351,    1,    1,    1,    1,    1,    1,    1,    1,    9,
      351,  351,  351,  351,  352,  351,  351,  351,  351,  351,
      351,  351,  351,  351,  351,  351,  351,  351,  353,  353,
      353,  353,  353,  353,  353,  353,  353,  353,  353,  353,
      353,  353,  353,  353,  353,  353,  353,  353,  353,  353,
      353,  353,  353,  353,  353,  353,  353,  353,  353,  353,
      353,  351,  352,  351,  354,  351,  351,  351,  351,  351,
      351,  353,  353,  353,  353,  353,  353,  353,  353,  353,
      353,  353,  353,  353,  353,  353,  353,  353,  353,  353,
      353,  353,  353,  353,  353,  353,  353,  353,  353,  353,

      353,  353,  353,  353,  353,  353,  353,  353,  353,  353,
      353,  353,  353,  353,  353,  353,  353,  353,  353,  353,
      353,  353,  354,  351,  353,  353,  353,  353,  353,  353,
      353,  353,  353,  353,  353,  353,  353,  353,  353,  353,
      353,  353,  353,  353,  353,  353,  353,  353,  353,  353,
      353,  353,  353,  353,  353,  353,  353,  353,  353,  353,
      353,  353,  353,  353,  353,  353,  353,  353,  353,  353,
      353,  353,  353,  351,  353,  353,  353,  353,  353,  353,
      353,  353,  353,  353,  353,  353,  353,  353,  353,  353,
      353,  353,  353,  353,  353,  353,  353,  353,  353,  353,

      353,  353,  353,  353,  353,  353,  353,  353,  353,  353,
      353,  353,  353,  353,  353,  351,  351,  353,  353,  353,
      353,  353,  353,  353,  353,  353,  353,  353,  353,  353,
      353,  353,  353,  353,  353,  353,  353,  353,  353,  353,
      353,  353,  353,  353,  353,  353,  353,  353,  353,  353,
      353,  353,  353,  353,  353,  353,  353,  353,  353,  353,
      353,  353,  353,  353,  353,  353,  353,  353,  353,  353,
      353,  353,  353,  353,  353,  353,  353,  353,  353,  353,
      353,  353,  353,  353,  353,  353,  353,  353,  353,  353,
      353,  353,  353,  353,  353,  353,  353,  353,  353,  353,

      353,  353,  353,  353,  353,  353,  353,  353,  353,  353,
      353,  353,  353,  353,  353,  353,  353,  353,  353,  353,
      353,  353,  353,  353,  353,  353,  353,  353,  353,  353,
      353,  353,  353,  353,  353,  353,  353,  353,  353,  353,
      353,  353,  353,  353,  353,  353,  353,  353,  353,  353,
        0,  351,  351,  351
    } ;

static yyconst flex_uint16_t yy_nxt[898] =
    {   0,
       12,   13,   14,   15,   16,   17,   18,   19,   20,   12,
       21,   22,   23,   24,   24,   25,   25,   25,   25,   26,
       27,   28,   12,   20,   29,   30,   31,   32,   33,   34,
       35,   36,   37,   36,   36,   38,   36,   36,   39,   40,
       41,   42,   43,   44,   36,   36,   45,   36,   36,   20,
       29,   30,   31,   32,   33,   34,   35,   36,   37,   36,
       38,   36,   36,   39,   40,   41,   42,   43,   44,   36,
       36,   45,   36,   36,   46,   47,   46,   47,   80,   72,
       82,   48,   84,   48,  342,   83,  104,   49,   81,   49,
       66,   68,   68,   68,   68,   68,   68,   50,  125,   50,

       46,   47,   46,   47,   80,   82,  339,   48,   84,   48,
       83,  104,   49,   81,   49,   66,   67,   67,   68,   68,
       68,   68,   50,  125,   50,   51,   52,   85,   53,  334,
       73,   90,   54,  297,  298,   74,  329,   75,   55,   56,
       57,   58,  121,   59,  104,   91,   60,  322,   61,   69,
       76,   51,   52,   85,   53,   73,   77,   90,   54,   78,
       74,   79,   75,   55,   56,   57,   58,  121,   59,  104,
       91,   60,   88,   61,   69,   86,   76,  320,   89,   87,
       92,   77,   98,  313,   78,   96,   79,   93,   94,   97,
      105,  105,   99,  100,   95,   80,  122,  310,   88,  131,

       86,  308,  107,   89,   87,  108,   92,  101,   98,  102,
      126,   96,  127,   93,   94,   97,  103,   99,  100,   95,
      106,   80,  122,  105,  109,  131,   77,  107,   87,   78,
      108,   79,  101,  128,  102,  126,  112,  127,  292,  110,
      132,  103,   77,   90,  276,   78,  106,   79,  105,  109,
       83,   77,  269,   87,   78,  238,   79,  111,  128,  114,
      113,  223,  112,  129,   80,  110,  132,   77,  133,   90,
       78,  107,   79,  115,  108,   83,  134,   87,  130,  110,
       92,   96,  111,   90,  114,   97,  113,   93,  117,  129,
       80,  116,  135,  133,  118,  138,  107,  111,  115,  108,

      119,  134,   87,  130,  221,  110,   92,   96,  198,   90,
      120,   97,  192,   93,  117,  177,  116,  135,   98,  118,
      138,   64,  111,  105,  105,  119,   69,   69,   99,  100,
      124,  124,  124,  124,  124,  124,  120,   66,   67,   67,
       68,   68,   68,   68,   98,   66,   68,   68,   68,   68,
       68,   68,  136,   99,  100,  139,  105,  140,  141,   69,
      142,  143,  144,   62,  145,  146,  149,  137,  147,  148,
      155,   69,  150,  151,  152,  154,   71,  156,  136,  157,
      139,  105,  140,  141,   69,  142,  143,  153,  144,  145,
      146,  149,  137,  147,  148,  155,   69,  159,  150,  151,

      152,  154,  156,  105,  105,  157,  158,   70,  160,  140,
      161,  165,  153,  162,  163,  164,  166,  167,  146,  140,
      161,  128,  159,  168,  169,   65,  128,  147,  148,  170,
      171,  172,  158,  160,  140,  161,  105,  165,  162,  163,
      164,  166,  167,  146,  140,  161,  128,  173,  168,  175,
      169,  128,  147,  148,  170,  171,  176,  172,  178,  179,
      181,  105,  124,  124,  124,  124,  124,  124,  180,  182,
      183,  184,  173,  185,  187,  175,  186,  174,   64,  188,
      189,  176,  190,  178,  191,  179,  181,  193,  194,  195,
       62,  196,  197,  180,  182,  183,  184,  199,  201,  185,

      187,  186,  200,  174,  188,  189,  202,  190,  203,  191,
      204,  207,  193,  206,  194,  195,  196,  197,  183,  205,
      208,  351,  209,  199,  201,  210,  211,  200,  212,  213,
      351,  214,  202,  215,  203,  218,  204,  207,  206,  344,
      345,  219,  222,  183,  205,  220,  208,  209,  224,  225,
      226,  210,  211,  227,  212,  213,  214,  216,  215,  216,
      218,  217,  217,  217,  217,  217,  217,  219,  222,  228,
      220,  229,  230,  224,  225,  226,  231,  232,  235,  227,
      233,  234,  236,  237,  351,  239,  240,  241,  242,  243,
      244,  245,  246,  247,  228,  248,  229,  249,  230,  245,

      250,  251,  231,  232,  235,  233,  234,  236,  252,  237,
      239,  240,  241,  242,  243,  244,  245,  246,  247,  351,
      248,  253,  249,  254,  245,  250,  255,  251,  256,  257,
      258,  351,  259,  252,  217,  217,  217,  217,  217,  217,
      217,  217,  217,  217,  217,  217,  260,  253,  261,  254,
      262,  263,  255,  256,  264,  257,  258,  259,  265,  266,
      267,  351,  268,  270,  351,  271,  272,  273,  274,  275,
      277,  260,  278,  279,  261,  280,  262,  263,  281,  282,
      264,  283,  284,  285,  265,  266,  267,  268,  286,  270,
      271,  272,  273,  274,  275,  277,  287,  278,  279,  288,

      289,  280,  290,  281,  291,  282,  283,  284,  285,  293,
      351,  294,  295,  296,  286,  299,  351,  301,  302,  303,
      304,  300,  287,  305,  309,  288,  289,  290,  306,  291,
      307,  311,  312,  314,  315,  293,  294,  316,  295,  296,
      317,  299,  301,  302,  303,  304,  300,  318,  332,  305,
      309,  319,  321,  306,  323,  307,  311,  312,  314,  315,
      324,  325,  326,  316,  327,  317,  328,  330,  331,  333,
      335,  336,  338,  318,  332,  337,  319,  321,  340,  323,
      341,  343,  346,  347,  348,  324,  325,  326,  349,  327,
      350,  328,  330,  331,  333,  335,  351,  336,  338,  351,

      337,  351,  351,  340,  351,  341,  343,  346,  347,  351,
      348,  351,  351,  351,  349,  350,   63,  351,   63,  123,
      351,  123,   11,  351,  351,  351,  351,  351,  351,  351,
      351,  351,  351,  351,  351,  351,  351,  351,  351,  351,
      351,  351,  351,  351,  351,  351,  351,  351,  351,  351,
      351,  351,  351,  351,  351,  351,  351,  351,  351,  351,
      351,  351,  351,  351,  351,  351,  351,  351,  351,  351,
      351,  351,  351,  351,  351,  351,  351,  351,  351,  351,
      351,  351,  351,  351,  351,  351,  351,  351,  351,  351,
      351,  351,  351,  351,  351,  351,  351

    } ;

static yyconst flex_int16_t yy_chk[898] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    5,    5,    6,    6,   31,  353,
       32,    5,   34,    6,  337,   33,   44,    5,   31,    6,
       25,   25,   25,   25,   25,   25,   25,    5,   73,    6,

        5,    5,    6,    6,   31,   32,  334,    5,   34,    6,
       33,   44,    5,   31,    6,   24,   24,   24,   24,   24,
       24,   24,    5,   73,    6,    9,    9,   35,    9,  329,
       29,   39,    9,  275,  275,   29,  322,   29,    9,    9,
        9,    9,   59,    9,   59,   39,    9,  310,    9,   24,
       30,    9,    9,   35,    9,   29,   30,   39,    9,   30,
       29,   30,   29,    9,    9,    9,    9,   59,    9,   59,
       39,    9,   38,    9,   24,   37,   30,  307,   38,   37,
       40,   30,   42,  296,   30,   41,   30,   40,   40,   41,
       45,   45,   42,   42,   40,   47,   61,  292,   38,   78,

       37,  290,   47,   38,   37,   47,   40,   43,   42,   43,
       74,   41,   75,   40,   40,   41,   43,   42,   42,   40,
       46,   47,   61,   45,   48,   78,   46,   47,   48,   46,
       47,   46,   43,   76,   43,   74,   51,   75,  269,   49,
       79,   43,   51,   49,  248,   51,   46,   51,   45,   48,
       53,   46,  238,   48,   46,  198,   46,   49,   76,   53,
       52,  182,   51,   77,   52,   49,   79,   51,   80,   49,
       51,   52,   51,   54,   52,   53,   81,   54,   77,   55,
       56,   57,   49,   55,   53,   57,   52,   56,   56,   77,
       52,   55,   82,   80,   56,   84,   52,   55,   54,   52,

       57,   81,   54,   77,  180,   55,   56,   57,  152,   55,
       58,   57,  146,   56,   56,  128,   55,   82,   58,   56,
       84,   63,   55,   60,   60,   57,   69,   69,   58,   58,
       66,   66,   66,   66,   66,   66,   58,   67,   67,   67,
       67,   67,   67,   67,   58,   68,   68,   68,   68,   68,
       68,   68,   83,   58,   58,   85,   60,   86,   88,   69,
       89,   91,   92,   62,   93,   94,   96,   83,   95,   95,
      102,   67,   97,   98,   99,  100,   28,  103,   83,  104,
       85,   60,   86,   88,   69,   89,   91,   99,   92,   93,
       94,   96,   83,   95,   95,  102,   67,  107,   97,   98,

       99,  100,  103,  105,  105,  104,  106,   26,  108,  109,
      109,  112,   99,  109,  110,  111,  113,  114,  117,  115,
      115,  106,  107,  115,  116,   22,  112,  118,  118,  119,
      120,  121,  106,  108,  109,  109,  105,  112,  109,  110,
      111,  113,  114,  117,  115,  115,  106,  122,  115,  126,
      116,  112,  118,  118,  119,  120,  127,  121,  129,  130,
      132,  105,  124,  124,  124,  124,  124,  124,  131,  133,
      134,  135,  122,  137,  139,  126,  138,  124,   15,  140,
      141,  127,  144,  129,  145,  130,  132,  147,  148,  149,
       13,  150,  151,  131,  133,  134,  135,  153,  155,  137,

      139,  138,  154,  124,  140,  141,  156,  144,  158,  145,
      159,  162,  147,  161,  148,  149,  150,  151,  160,  160,
      163,   11,  164,  153,  155,  165,  167,  154,  168,  170,
        0,  171,  156,  173,  158,  175,  159,  162,  161,  339,
      339,  176,  181,  160,  160,  177,  163,  164,  183,  184,
      185,  165,  167,  186,  168,  170,  171,  174,  173,  174,
      175,  174,  174,  174,  174,  174,  174,  176,  181,  187,
      177,  188,  189,  183,  184,  185,  190,  191,  195,  186,
      192,  194,  196,  197,    0,  199,  200,  203,  204,  205,
      206,  207,  208,  209,  187,  210,  188,  211,  189,  212,

      212,  213,  190,  191,  195,  192,  194,  196,  214,  197,
      199,  200,  203,  204,  205,  206,  207,  208,  209,    0,
      210,  219,  211,  220,  212,  212,  221,  213,  222,  223,
      224,    0,  225,  214,  216,  216,  216,  216,  216,  216,
      217,  217,  217,  217,  217,  217,  226,  219,  228,  220,
      230,  231,  221,  222,  232,  223,  224,  225,  233,  234,
      236,    0,  237,  239,    0,  240,  243,  245,  246,  247,
      249,  226,  250,  251,  228,  252,  230,  231,  253,  254,
      232,  255,  257,  258,  233,  234,  236,  237,  261,  239,
      240,  243,  245,  246,  247,  249,  262,  250,  251,  263,

      264,  252,  265,  253,  266,  254,  255,  257,  258,  271,
        0,  272,  273,  274,  261,  276,    0,  279,  281,  282,
      283,  276,  262,  284,  291,  263,  264,  265,  285,  266,
      289,  294,  295,  299,  300,  271,  272,  302,  273,  274,
      303,  276,  279,  281,  282,  283,  276,  304,  327,  284,
      291,  305,  308,  285,  313,  289,  294,  295,  299,  300,
      315,  317,  318,  302,  320,  303,  321,  323,  326,  328,
      330,  331,  333,  304,  327,  332,  305,  308,  335,  313,
      336,  338,  341,  342,  343,  315,  317,  318,  347,  320,
      349,  321,  323,  326,  328,  330,    0,  331,  333,    0,

      332,    0,    0,  335,    0,  336,  338,  341,  342,    0,
      343,    0,    0,    0,  347,  349,  352,    0,  352,  354,
        0,  354,  351,  351,  351,  351,  351,  351,  351,  351,
      351,  351,  351,  351,  351,  351,  351,  351,  351,  351,
      351,  351,  351,  351,  351,  351,  351,  351,  351,  351,
      351,  351,  351,  351,  351,  351,  351,  351,  351,  351,
      351,  351,  351,  351,  351,  351,  351,  351,  351,  351,
      351,  351,  351,  351,  351,  351,  351,  351,  351,  351,
      351,  351,  351,  351,  351,  351,  351,  351,  351,  351,
      351,  351,  351,  351,  351,  351,  351

    } ;

#define REJECT \
{ \
*yy_cp = yyg->yy_hold_char; /* undo effects of setting up yytext */ \
yy_cp = yyg->yy_full_match; /* restore poss. backed-over text */ \
++yyg->yy_lp; \
goto find_rule; \
}

#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
#line 1 "vhdl_flex.l"
/*
 * $Id$
 *
 * Original Lex source by Ken Parker, 1990
 * Extensions and adaptions for UrJTAG by Arnim Laeuger, 2007
 *
 */
/*----------------------------------------------------------
 *
 *  Lex source for BSDL
 *
 *----------------------------------------------------------*/
/* Date:   901003 */
/*

Email header accompanying the original Yacc code:
  http://www.eda.org/vug_bbs/bsdl.parser

-----------------------------------8<--------------------------------------

Hello All,

This is this first mailing of the BSDL* Version 0.0 parser specifications
we are sending to people who request it from our publicized E-Mail address;

             bsdl%hpmtlx@hplabs.HP.com

You are free to redistribute this at will, but we feel that it would be
better if respondents asked for it directly so that their addresses can
be entered into our list for future mailings and updates.

It would be helpful if you could confirm receipt of this transmission.
We also would be very interested to hear about your experiences with this
information and what you are planning to do with BSDL.

Regards,

Ken Parker
Hewlett-Packard Company


*Boundary-Scan Description Language - as documented in:

"A Language for Describing Boundary-Scan Devices", K.P. Parker
and S. Oresjo, Proceedings 1990 International Test Conference,
Washington DC, pp 222-234


- -----------------cut here---------------------------------------------------


901004.0721                                  Hewlett-Packard Company
901016.1049                                  Manufacturing Test Division
                                             P.O. Box 301
                                             Loveland, Colorado  80537
                                             USA

                                                             October 1990
Hello BSDL Parser Requestor,

   This Electronic Mail reply contains the computer specifications for
Hewlett-Packard's Version 0.0 BSDL parser.  This section of the reply
explains the contents of the rest of this file.

This file is composed of seven (7) parts:

   1) How to use this file

   2) UNIX* Lex source  (lexicographical tokenizing rules)

   3) UNIX* Yacc source (BNF-like syntax description)

   4) A sample main program to recognize BSDL.

   5) A BSDL description of the Texas Instruments 74bct8374 that is
      recognized by the parser, for testing purposes.

   6) The VHDL package STD_1149_1_1990 needed by this parser.

   7) [added 901016] Porting experiences to other systems.


RECOMMENDATION: Save a copy of this file in archival storage before
                processing it via the instructions below.  This will
                allow you to recover from errors, and allow you to
                compare subsequently released data for changes.

DISCLAIMERS:

1.  The IEEE 1149.1 Working Group has not endorsed BSDL Version 0.0 and
    therefore no person may represent it as an IEEE standard or imply that
    a resulting IEEE standard will be identical to it.

2.  The IEEE 1149.1 Working Group recognizes that BSDL Version 0.0 is a
    well-conceived initiative that is likely to excelerate the creation
    of tools that support the 1149.1 standard.  As such, changes and
    enhancements will be carefully considered so as not to needlessly
    disrupt these development efforts.  The overriding goal is the
    ultimate success of the 1149.1 standard.

LEGAL NOTICES:

    Hewlett-Packard Company makes no warranty of any kind with regard to
    this information, including, but not limited to, the implied
    waranties of merchantability and fitness for a particular purpose.

    Hewlett-Packard Company shall not be liable for errors contained
    herein or direct, indirect, special, incidental, or consequential
    damages in connection with the furnishing, performance, or use of
    this material.


*UNIX is a trademark of AT&T in the USA and other countries.

*/
#line 125 "vhdl_flex.l"
/* Begin lex input specifications */
#include <sysdep.h>
/* Undef TRUE and FALSE to avoid redefinition error
   when compiling for Windows host.  */
#undef TRUE
#undef FALSE

#include <stdlib.h>
#include <ctype.h>

#include <urjtag/jtag.h>

#include "bsdl_sysdep.h"

#include "bsdl_msg.h"

#include "vhdl_bison.h"
#include "vhdl_parser.h"

#ifdef DMALLOC
#include "dmalloc.h"
#endif

#define YY_EXTRA_TYPE urj_bsdl_scan_extra_t *

static char *new_string (urj_bsdl_scan_extra_t *, const char *);

#define BINARY  0
#define DECIMAL 1
#define BIN_X   2

/* Fix up warnings from generated lex code */
#define lex_get_column urj_vhdl_get_column
#define lex_set_column urj_vhdl_set_column
#include "lex.h"


#line 971 "vhdl_flex.c"

#define INITIAL 0
#define RES 1
#define BOU 2
#define REG 3
#define PAC 4

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

/* Holds the entire state of the reentrant scanner. */
struct yyguts_t
    {

    /* User-defined. Not touched by flex. */
    YY_EXTRA_TYPE yyextra_r;

    /* The rest are the same as the globals declared in the non-reentrant scanner. */
    FILE *yyin_r, *yyout_r;
    size_t yy_buffer_stack_top; /**< index of top of stack. */
    size_t yy_buffer_stack_max; /**< capacity of stack. */
    YY_BUFFER_STATE * yy_buffer_stack; /**< Stack as an array. */
    char yy_hold_char;
    int yy_n_chars;
    yy_size_t yyleng_r;
    char *yy_c_buf_p;
    int yy_init;
    int yy_start;
    int yy_did_buffer_switch_on_eof;
    int yy_start_stack_ptr;
    int yy_start_stack_depth;
    int *yy_start_stack;
    yy_state_type yy_last_accepting_state;
    char* yy_last_accepting_cpos;

    int yylineno_r;
    int yy_flex_debug_r;

    yy_state_type *yy_state_buf;
    yy_state_type *yy_state_ptr;
    char *yy_full_match;
    int yy_lp;

    /* These are only needed for trailing context rules,
     * but there's no conditional variable for that yet. */
    int yy_looking_for_trail_begin;
    int yy_full_lp;
    int *yy_full_state;

    char *yytext_r;
    int yy_more_flag;
    int yy_more_len;

    YYSTYPE * yylval_r;

    }; /* end struct yyguts_t */

static int yy_init_globals (yyscan_t yyscanner );

    /* This must go here because YYSTYPE and YYLTYPE are included
     * from bison output in section 1.*/
    #    define yylval yyg->yylval_r
    
int urj_vhdl_lex_init (yyscan_t* scanner);

int urj_vhdl_lex_init_extra (YY_EXTRA_TYPE user_defined,yyscan_t* scanner);

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int urj_vhdl_lex_destroy (yyscan_t yyscanner );

int urj_vhdl_get_debug (yyscan_t yyscanner );

void urj_vhdl_set_debug (int debug_flag ,yyscan_t yyscanner );

YY_EXTRA_TYPE urj_vhdl_get_extra (yyscan_t yyscanner );

void urj_vhdl_set_extra (YY_EXTRA_TYPE user_defined ,yyscan_t yyscanner );

FILE *urj_vhdl_get_in (yyscan_t yyscanner );

void urj_vhdl_set_in  (FILE * _in_str ,yyscan_t yyscanner );

FILE *urj_vhdl_get_out (yyscan_t yyscanner );

void urj_vhdl_set_out  (FILE * _out_str ,yyscan_t yyscanner );

yy_size_t urj_vhdl_get_leng (yyscan_t yyscanner );

char *urj_vhdl_get_text (yyscan_t yyscanner );

int urj_vhdl_get_lineno (yyscan_t yyscanner );

void urj_vhdl_set_lineno (int _line_number ,yyscan_t yyscanner );

int urj_vhdl_get_column  (yyscan_t yyscanner );

void urj_vhdl_set_column (int _column_no ,yyscan_t yyscanner );

YYSTYPE * urj_vhdl_get_lval (yyscan_t yyscanner );

void urj_vhdl_set_lval (YYSTYPE * yylval_param ,yyscan_t yyscanner );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int urj_vhdl_wrap (yyscan_t yyscanner );
#else
extern int urj_vhdl_wrap (yyscan_t yyscanner );
#endif
#endif

#ifndef YY_NO_UNPUT
    
    static void yyunput (int c,char *buf_ptr  ,yyscan_t yyscanner);
    
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy (char *,yyconst char *,int ,yyscan_t yyscanner);
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * ,yyscan_t yyscanner);
#endif

#ifndef YY_NO_INPUT

#ifdef __cplusplus
static int yyinput (yyscan_t yyscanner );
#else
static int input (yyscan_t yyscanner );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, yyleng, 1, yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		size_t n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = fread(buf, 1, max_size, yyin))==0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg , yyscanner)
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int urj_vhdl_lex \
               (YYSTYPE * yylval_param ,yyscan_t yyscanner);

#define YY_DECL int urj_vhdl_lex \
               (YYSTYPE * yylval_param , yyscan_t yyscanner)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK /*LINTED*/break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	yy_state_type yy_current_state;
	char *yy_cp, *yy_bp;
	int yy_act;
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

    yylval = yylval_param;

	if ( !yyg->yy_init )
		{
		yyg->yy_init = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

        /* Create the reject buffer large enough to save one state per allowed character. */
        if ( ! yyg->yy_state_buf )
            yyg->yy_state_buf = (yy_state_type *)urj_vhdl_alloc(YY_STATE_BUF_SIZE  ,yyscanner);
            if ( ! yyg->yy_state_buf )
                YY_FATAL_ERROR( "out of dynamic memory in urj_vhdl_lex()" );

		if ( ! yyg->yy_start )
			yyg->yy_start = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			urj_vhdl_ensure_buffer_stack (yyscanner);
			YY_CURRENT_BUFFER_LVALUE =
				urj_vhdl__create_buffer(yyin,YY_BUF_SIZE ,yyscanner);
		}

		urj_vhdl__load_buffer_state(yyscanner );
		}

	{
#line 252 "vhdl_flex.l"

#line 1269 "vhdl_flex.c"

	while ( /*CONSTCOND*/1 )		/* loops until end-of-file is reached */
		{
		yy_cp = yyg->yy_c_buf_p;

		/* Support of yytext. */
		*yy_cp = yyg->yy_hold_char;

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = yyg->yy_start;

		yyg->yy_state_ptr = yyg->yy_state_buf;
		*yyg->yy_state_ptr++ = yy_current_state;

yy_match:
		do
			{
			YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)] ;
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 352 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			*yyg->yy_state_ptr++ = yy_current_state;
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 823 );

yy_find_action:
		yy_current_state = *--yyg->yy_state_ptr;
		yyg->yy_lp = yy_accept[yy_current_state];
find_rule: /* we branch to this label when backing up */
		for ( ; ; ) /* until we find what rule we matched */
			{
			if ( yyg->yy_lp && yyg->yy_lp < yy_accept[yy_current_state + 1] )
				{
				yy_act = yy_acclist[yyg->yy_lp];
					{
					yyg->yy_full_match = yy_cp;
					break;
					}
				}
			--yy_cp;
			yy_current_state = *--yyg->yy_state_ptr;
			yyg->yy_lp = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
case 1:
YY_RULE_SETUP
#line 253 "vhdl_flex.l"
{return (ENTITY); }
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 254 "vhdl_flex.l"
{yyextra->Base = DECIMAL;  /* Default number base */
                         return (PORT); }
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 256 "vhdl_flex.l"
{yyextra->Base = DECIMAL; return (GENERIC); }
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 257 "vhdl_flex.l"
{yyextra->Base = DECIMAL; return (USE); }
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 258 "vhdl_flex.l"
{yyextra->Base = DECIMAL; return (ATTRIBUTE); }
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 259 "vhdl_flex.l"
{return (IS); }
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 260 "vhdl_flex.l"
{yyextra->Base = DECIMAL; return (CONSTANT); }
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 261 "vhdl_flex.l"
{return (STRING); }
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 262 "vhdl_flex.l"
{yyextra->Base = DECIMAL;
                         BEGIN INITIAL; /* Turn off start conditions */
                         return (END); }
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 265 "vhdl_flex.l"
{return (ALL); }
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 266 "vhdl_flex.l"
{return (OF); }
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 267 "vhdl_flex.l"
{return (PHYSICAL_PIN_MAP); }
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 268 "vhdl_flex.l"
{return (PIN_MAP_STRING); }
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 269 "vhdl_flex.l"
{return (TRUE); }
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 270 "vhdl_flex.l"
{return (FALSE); }
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 271 "vhdl_flex.l"
{return (SIGNAL); }
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 272 "vhdl_flex.l"
{return (LOW); }
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 273 "vhdl_flex.l"
{return (BOTH); }
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 274 "vhdl_flex.l"
{return (IN); }
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 275 "vhdl_flex.l"
{return (OUT); }
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 276 "vhdl_flex.l"
{return (INOUT); }
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 277 "vhdl_flex.l"
{return (BUFFER); }
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 278 "vhdl_flex.l"
{return (LINKAGE); }
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 279 "vhdl_flex.l"
{return (BIT); }
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 280 "vhdl_flex.l"
{return (BIT_VECTOR); }
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 281 "vhdl_flex.l"
{return (TO); }
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 282 "vhdl_flex.l"
{return (DOWNTO); }
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 283 "vhdl_flex.l"
{return (PACKAGE); }
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 284 "vhdl_flex.l"
{return (BODY); }
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 285 "vhdl_flex.l"
{return (TYPE); }
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 286 "vhdl_flex.l"
{return (SUBTYPE); }
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 287 "vhdl_flex.l"
{return (RECORD); }
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 288 "vhdl_flex.l"
{yyextra->Base = DECIMAL; return (ARRAY); }
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 289 "vhdl_flex.l"
{return (POSITIVE); }
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 290 "vhdl_flex.l"
{return (RANGE); }
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 291 "vhdl_flex.l"
{BEGIN PAC; return (CELL_INFO); }
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 292 "vhdl_flex.l"
{return (BSDL_EXTENSION); }
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 293 "vhdl_flex.l"
{return (STD_1532_2001); }
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 294 "vhdl_flex.l"
{return (STD_1532_2002); }
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 295 "vhdl_flex.l"
{return (INPUT); }
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 296 "vhdl_flex.l"
{return (OUTPUT2); }
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 297 "vhdl_flex.l"
{return (OUTPUT3); }
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 298 "vhdl_flex.l"
{return (CONTROLR); }
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 299 "vhdl_flex.l"
{return (CONTROL); }
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 300 "vhdl_flex.l"
{return (INTERNAL); }
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 301 "vhdl_flex.l"
{return (CLOCK); }
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 302 "vhdl_flex.l"
{return (OBSERVE_ONLY); }
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 303 "vhdl_flex.l"
{return (BIDIR); }
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 304 "vhdl_flex.l"
{return (BIDIR_IN); }
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 305 "vhdl_flex.l"
{return (BIDIR_OUT); }
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 306 "vhdl_flex.l"
{return (EXTEST); }
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 307 "vhdl_flex.l"
{return (SAMPLE); }
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 308 "vhdl_flex.l"
{return (INTEST); }
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 309 "vhdl_flex.l"
{return (RUNBIST); }
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 310 "vhdl_flex.l"
{return (PI); }
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 311 "vhdl_flex.l"
{return (PO); }
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 312 "vhdl_flex.l"
{return (UPD); }
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 313 "vhdl_flex.l"
{return (CAP); }
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 314 "vhdl_flex.l"
{return (X); }
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 315 "vhdl_flex.l"
{return (ZERO); }
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 316 "vhdl_flex.l"
{return (ONE); }
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 317 "vhdl_flex.l"
{return (Z); }
	YY_BREAK
case 63:
/* rule 63 can match eol */
YY_RULE_SETUP
#line 318 "vhdl_flex.l"
{yylineno++; /* Count lines */}
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 319 "vhdl_flex.l"
{return (COMMA); }
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 320 "vhdl_flex.l"
{return (LPAREN);}
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 321 "vhdl_flex.l"
{return (RPAREN);}
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 322 "vhdl_flex.l"
{return (PERIOD); }
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 323 "vhdl_flex.l"
{return (COLON);  }
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 324 "vhdl_flex.l"
{return (BOX);  }
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 325 "vhdl_flex.l"
{yyextra->Base = BIN_X; return (SINGLE_QUOTE); }
	YY_BREAK
case 71:
YY_RULE_SETUP
#line 326 "vhdl_flex.l"
{return (COLON_EQUAL); }
	YY_BREAK
case 72:
YY_RULE_SETUP
#line 327 "vhdl_flex.l"
{ /* Do Nothing on White Space */ }
	YY_BREAK
case 73:
YY_RULE_SETUP
#line 328 "vhdl_flex.l"
{ /* Do Nothing on Comments    */ }
	YY_BREAK
case 74:
YY_RULE_SETUP
#line 329 "vhdl_flex.l"
{if (yyextra->Base != BIN_X) REJECT;
                         yylval->str = new_string (yyextra, yytext);
                         return (BIN_X_PATTERN);}
	YY_BREAK
case 75:
YY_RULE_SETUP
#line 332 "vhdl_flex.l"
{yylval->str = new_string (yyextra, yytext);
                         return (IDENTIFIER); }
	YY_BREAK
case 76:
YY_RULE_SETUP
#line 334 "vhdl_flex.l"
{yylval->str = new_string (yyextra, yytext);
                         return (QUOTED_STRING); }
	YY_BREAK
case 77:
YY_RULE_SETUP
#line 336 "vhdl_flex.l"
{if (yyextra->Base != DECIMAL) REJECT;
                         yylval->integer = atoi ((char *)yytext);
                         return (DECIMAL_NUMBER);}
	YY_BREAK
case 78:
YY_RULE_SETUP
#line 339 "vhdl_flex.l"
{yylval->str = new_string (yyextra, yytext);
                         return (REAL_NUMBER);}
	YY_BREAK
case 79:
YY_RULE_SETUP
#line 341 "vhdl_flex.l"
{return (CONCATENATE);}
	YY_BREAK
case 80:
YY_RULE_SETUP
#line 342 "vhdl_flex.l"
{return (SEMICOLON);}
	YY_BREAK
case 81:
YY_RULE_SETUP
#line 343 "vhdl_flex.l"
{urj_bsdl_err_set (yyextra->proc_mode, URJ_ERROR_BSDL_VHDL,
                                           "Illegal character %c (/%03o) at line %d:",
                                           (char)yytext[yyleng-1], (int)yytext[yyleng-1],
                                           yylineno);
                         yyextra->Compile_Errors++;
                         return (ILLEGAL);  /* Will cause syntax error */}
	YY_BREAK
case YY_STATE_EOF(INITIAL):
case YY_STATE_EOF(RES):
case YY_STATE_EOF(BOU):
case YY_STATE_EOF(REG):
case YY_STATE_EOF(PAC):
#line 349 "vhdl_flex.l"
{
  urj_vhdl_pop_buffer_state (yyscanner);
  if (!YY_CURRENT_BUFFER)
    yyterminate();
}
	YY_BREAK
case 82:
YY_RULE_SETUP
#line 355 "vhdl_flex.l"
ECHO;
	YY_BREAK
#line 1767 "vhdl_flex.c"

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - yyg->yytext_ptr) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = yyg->yy_hold_char;
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * urj_vhdl_lex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			yyg->yy_n_chars = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( yyg->yy_c_buf_p <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[yyg->yy_n_chars] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			yyg->yy_c_buf_p = yyg->yytext_ptr + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state( yyscanner );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state , yyscanner);

			yy_bp = yyg->yytext_ptr + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++yyg->yy_c_buf_p;
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = yyg->yy_c_buf_p;
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer( yyscanner ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				yyg->yy_did_buffer_switch_on_eof = 0;

				if ( urj_vhdl_wrap(yyscanner ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					yyg->yy_c_buf_p = yyg->yytext_ptr + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! yyg->yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				yyg->yy_c_buf_p =
					yyg->yytext_ptr + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state( yyscanner );

				yy_cp = yyg->yy_c_buf_p;
				yy_bp = yyg->yytext_ptr + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				yyg->yy_c_buf_p =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[yyg->yy_n_chars];

				yy_current_state = yy_get_previous_state( yyscanner );

				yy_cp = yyg->yy_c_buf_p;
				yy_bp = yyg->yytext_ptr + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of user's declarations */
} /* end of urj_vhdl_lex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
	char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	char *source = yyg->yytext_ptr;
	yy_size_t number_to_move, i;
	int ret_val;

	if ( yyg->yy_c_buf_p > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[yyg->yy_n_chars + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( yyg->yy_c_buf_p - yyg->yytext_ptr - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (yy_size_t) (yyg->yy_c_buf_p - yyg->yytext_ptr) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = yyg->yy_n_chars = 0;

	else
		{
			yy_size_t num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			YY_FATAL_ERROR(
"input buffer overflow, can't enlarge buffer because scanner uses REJECT" );

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			yyg->yy_n_chars, num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = yyg->yy_n_chars;
		}

	if ( yyg->yy_n_chars == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			urj_vhdl_restart(yyin  ,yyscanner);
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if ((int) (yyg->yy_n_chars + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		int new_size = yyg->yy_n_chars + number_to_move + (yyg->yy_n_chars >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) urj_vhdl_realloc((void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf,new_size ,yyscanner );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
	}

	yyg->yy_n_chars += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[yyg->yy_n_chars] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[yyg->yy_n_chars + 1] = YY_END_OF_BUFFER_CHAR;

	yyg->yytext_ptr = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (yyscan_t yyscanner)
{
	yy_state_type yy_current_state;
	char *yy_cp;
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

	yy_current_state = yyg->yy_start;

	yyg->yy_state_ptr = yyg->yy_state_buf;
	*yyg->yy_state_ptr++ = yy_current_state;

	for ( yy_cp = yyg->yytext_ptr + YY_MORE_ADJ; yy_cp < yyg->yy_c_buf_p; ++yy_cp )
		{
		YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 352 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		*yyg->yy_state_ptr++ = yy_current_state;
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state , yyscan_t yyscanner)
{
	int yy_is_jam;
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner; /* This var may be unused depending upon options. */

	YY_CHAR yy_c = 1;
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 352 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 351);
	if ( ! yy_is_jam )
		*yyg->yy_state_ptr++ = yy_current_state;

	(void)yyg;
	return yy_is_jam ? 0 : yy_current_state;
}

#ifndef YY_NO_UNPUT

    static void yyunput (int c, char * yy_bp , yyscan_t yyscanner)
{
	char *yy_cp;
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

    yy_cp = yyg->yy_c_buf_p;

	/* undo effects of setting up yytext */
	*yy_cp = yyg->yy_hold_char;

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		yy_size_t number_to_move = yyg->yy_n_chars + 2;
		char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			yyg->yy_n_chars = YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

	yyg->yytext_ptr = yy_bp;
	yyg->yy_hold_char = *yy_cp;
	yyg->yy_c_buf_p = yy_cp;
}

#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (yyscan_t yyscanner)
#else
    static int input  (yyscan_t yyscanner)
#endif

{
	int c;
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

	*yyg->yy_c_buf_p = yyg->yy_hold_char;

	if ( *yyg->yy_c_buf_p == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( yyg->yy_c_buf_p < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[yyg->yy_n_chars] )
			/* This was really a NUL. */
			*yyg->yy_c_buf_p = '\0';

		else
			{ /* need more input */
			yy_size_t offset = yyg->yy_c_buf_p - yyg->yytext_ptr;
			++yyg->yy_c_buf_p;

			switch ( yy_get_next_buffer( yyscanner ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					urj_vhdl_restart(yyin ,yyscanner);

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( urj_vhdl_wrap(yyscanner ) )
						return EOF;

					if ( ! yyg->yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput(yyscanner);
#else
					return input(yyscanner);
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					yyg->yy_c_buf_p = yyg->yytext_ptr + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) yyg->yy_c_buf_p;	/* cast for 8-bit char's */
	*yyg->yy_c_buf_p = '\0';	/* preserve yytext */
	yyg->yy_hold_char = *++yyg->yy_c_buf_p;

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * @param yyscanner The scanner object.
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void urj_vhdl_restart  (FILE * input_file , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

	if ( ! YY_CURRENT_BUFFER ){
        urj_vhdl_ensure_buffer_stack (yyscanner);
		YY_CURRENT_BUFFER_LVALUE =
            urj_vhdl__create_buffer(yyin,YY_BUF_SIZE ,yyscanner);
	}

	urj_vhdl__init_buffer(YY_CURRENT_BUFFER,input_file ,yyscanner);
	urj_vhdl__load_buffer_state(yyscanner );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * @param yyscanner The scanner object.
 */
    void urj_vhdl__switch_to_buffer  (YY_BUFFER_STATE  new_buffer , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

	/* TODO. We should be able to replace this entire function body
	 * with
	 *		urj_vhdl_pop_buffer_state();
	 *		urj_vhdl_push_buffer_state(new_buffer);
     */
	urj_vhdl_ensure_buffer_stack (yyscanner);
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*yyg->yy_c_buf_p = yyg->yy_hold_char;
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = yyg->yy_c_buf_p;
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = yyg->yy_n_chars;
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	urj_vhdl__load_buffer_state(yyscanner );

	/* We don't actually know whether we did this switch during
	 * EOF (urj_vhdl_wrap()) processing, but the only time this flag
	 * is looked at is after urj_vhdl_wrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	yyg->yy_did_buffer_switch_on_eof = 1;
}

static void urj_vhdl__load_buffer_state  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
	yyg->yy_n_chars = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	yyg->yytext_ptr = yyg->yy_c_buf_p = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	yyg->yy_hold_char = *yyg->yy_c_buf_p;
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * @param yyscanner The scanner object.
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE urj_vhdl__create_buffer  (FILE * file, int  size , yyscan_t yyscanner)
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) urj_vhdl_alloc(sizeof( struct yy_buffer_state ) ,yyscanner );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in urj_vhdl__create_buffer()" );

	b->yy_buf_size = (yy_size_t)size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) urj_vhdl_alloc(b->yy_buf_size + 2 ,yyscanner );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in urj_vhdl__create_buffer()" );

	b->yy_is_our_buffer = 1;

	urj_vhdl__init_buffer(b,file ,yyscanner);

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with urj_vhdl__create_buffer()
 * @param yyscanner The scanner object.
 */
    void urj_vhdl__delete_buffer (YY_BUFFER_STATE  b , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		urj_vhdl_free((void *) b->yy_ch_buf ,yyscanner );

	urj_vhdl_free((void *) b ,yyscanner );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a urj_vhdl_restart() or at EOF.
 */
    static void urj_vhdl__init_buffer  (YY_BUFFER_STATE  b, FILE * file , yyscan_t yyscanner)

{
	int oerrno = errno;
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

	urj_vhdl__flush_buffer(b ,yyscanner);

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then urj_vhdl__init_buffer was _probably_
     * called from urj_vhdl_restart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * @param yyscanner The scanner object.
 */
    void urj_vhdl__flush_buffer (YY_BUFFER_STATE  b , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		urj_vhdl__load_buffer_state(yyscanner );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  @param yyscanner The scanner object.
 */
void urj_vhdl_push_buffer_state (YY_BUFFER_STATE new_buffer , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
	if (new_buffer == NULL)
		return;

	urj_vhdl_ensure_buffer_stack(yyscanner);

	/* This block is copied from urj_vhdl__switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*yyg->yy_c_buf_p = yyg->yy_hold_char;
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = yyg->yy_c_buf_p;
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = yyg->yy_n_chars;
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		yyg->yy_buffer_stack_top++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from urj_vhdl__switch_to_buffer. */
	urj_vhdl__load_buffer_state(yyscanner );
	yyg->yy_did_buffer_switch_on_eof = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  @param yyscanner The scanner object.
 */
void urj_vhdl_pop_buffer_state (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
	if (!YY_CURRENT_BUFFER)
		return;

	urj_vhdl__delete_buffer(YY_CURRENT_BUFFER ,yyscanner);
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if (yyg->yy_buffer_stack_top > 0)
		--yyg->yy_buffer_stack_top;

	if (YY_CURRENT_BUFFER) {
		urj_vhdl__load_buffer_state(yyscanner );
		yyg->yy_did_buffer_switch_on_eof = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void urj_vhdl_ensure_buffer_stack (yyscan_t yyscanner)
{
	yy_size_t num_to_alloc;
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

	if (!yyg->yy_buffer_stack) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
		num_to_alloc = 1; /* After all that talk, this was set to 1 anyways... */
		yyg->yy_buffer_stack = (struct yy_buffer_state**)urj_vhdl_alloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								, yyscanner);
		if ( ! yyg->yy_buffer_stack )
			YY_FATAL_ERROR( "out of dynamic memory in urj_vhdl_ensure_buffer_stack()" );
								  
		memset(yyg->yy_buffer_stack, 0, num_to_alloc * sizeof(struct yy_buffer_state*));
				
		yyg->yy_buffer_stack_max = num_to_alloc;
		yyg->yy_buffer_stack_top = 0;
		return;
	}

	if (yyg->yy_buffer_stack_top >= (yyg->yy_buffer_stack_max) - 1){

		/* Increase the buffer to prepare for a possible push. */
		yy_size_t grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = yyg->yy_buffer_stack_max + grow_size;
		yyg->yy_buffer_stack = (struct yy_buffer_state**)urj_vhdl_realloc
								(yyg->yy_buffer_stack,
								num_to_alloc * sizeof(struct yy_buffer_state*)
								, yyscanner);
		if ( ! yyg->yy_buffer_stack )
			YY_FATAL_ERROR( "out of dynamic memory in urj_vhdl_ensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset(yyg->yy_buffer_stack + yyg->yy_buffer_stack_max, 0, grow_size * sizeof(struct yy_buffer_state*));
		yyg->yy_buffer_stack_max = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * @param yyscanner The scanner object.
 * @return the newly allocated buffer state object. 
 */
YY_BUFFER_STATE urj_vhdl__scan_buffer  (char * base, yy_size_t  size , yyscan_t yyscanner)
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) urj_vhdl_alloc(sizeof( struct yy_buffer_state ) ,yyscanner );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in urj_vhdl__scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	urj_vhdl__switch_to_buffer(b ,yyscanner );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to urj_vhdl_lex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * @param yyscanner The scanner object.
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       urj_vhdl__scan_bytes() instead.
 */
YY_BUFFER_STATE urj_vhdl__scan_string (yyconst char * yystr , yyscan_t yyscanner)
{
    
	return urj_vhdl__scan_bytes(yystr,strlen(yystr) ,yyscanner);
}

/** Setup the input buffer state to scan the given bytes. The next call to urj_vhdl_lex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * @param yyscanner The scanner object.
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE urj_vhdl__scan_bytes  (yyconst char * yybytes, yy_size_t  _yybytes_len , yyscan_t yyscanner)
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	yy_size_t i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = _yybytes_len + 2;
	buf = (char *) urj_vhdl_alloc(n ,yyscanner );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in urj_vhdl__scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = urj_vhdl__scan_buffer(buf,n ,yyscanner);
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in urj_vhdl__scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yy_fatal_error (yyconst char* msg , yyscan_t yyscanner)
{
	struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
	(void)yyg;
	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = yyg->yy_hold_char; \
		yyg->yy_c_buf_p = yytext + yyless_macro_arg; \
		yyg->yy_hold_char = *yyg->yy_c_buf_p; \
		*yyg->yy_c_buf_p = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the user-defined data for this scanner.
 * @param yyscanner The scanner object.
 */
YY_EXTRA_TYPE urj_vhdl_get_extra  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    return yyextra;
}

/** Get the current line number.
 * @param yyscanner The scanner object.
 */
int urj_vhdl_get_lineno  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    
        if (! YY_CURRENT_BUFFER)
            return 0;
    
    return yylineno;
}

/** Get the current column number.
 * @param yyscanner The scanner object.
 */
int urj_vhdl_get_column  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    
        if (! YY_CURRENT_BUFFER)
            return 0;
    
    return yycolumn;
}

/** Get the input stream.
 * @param yyscanner The scanner object.
 */
FILE *urj_vhdl_get_in  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    return yyin;
}

/** Get the output stream.
 * @param yyscanner The scanner object.
 */
FILE *urj_vhdl_get_out  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    return yyout;
}

/** Get the length of the current token.
 * @param yyscanner The scanner object.
 */
yy_size_t urj_vhdl_get_leng  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    return yyleng;
}

/** Get the current token.
 * @param yyscanner The scanner object.
 */

char *urj_vhdl_get_text  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    return yytext;
}

/** Set the user-defined data. This data is never touched by the scanner.
 * @param user_defined The data to be associated with this scanner.
 * @param yyscanner The scanner object.
 */
void urj_vhdl_set_extra (YY_EXTRA_TYPE  user_defined , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    yyextra = user_defined ;
}

/** Set the current line number.
 * @param _line_number line number
 * @param yyscanner The scanner object.
 */
void urj_vhdl_set_lineno (int  _line_number , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

        /* lineno is only valid if an input buffer exists. */
        if (! YY_CURRENT_BUFFER )
           YY_FATAL_ERROR( "urj_vhdl_set_lineno called with no buffer" );
    
    yylineno = _line_number;
}

/** Set the current column.
 * @param _column_no column number
 * @param yyscanner The scanner object.
 */
void urj_vhdl_set_column (int  _column_no , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

        /* column is only valid if an input buffer exists. */
        if (! YY_CURRENT_BUFFER )
           YY_FATAL_ERROR( "urj_vhdl_set_column called with no buffer" );
    
    yycolumn = _column_no;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param _in_str A readable stream.
 * @param yyscanner The scanner object.
 * @see urj_vhdl__switch_to_buffer
 */
void urj_vhdl_set_in (FILE *  _in_str , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    yyin = _in_str ;
}

void urj_vhdl_set_out (FILE *  _out_str , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    yyout = _out_str ;
}

int urj_vhdl_get_debug  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    return yy_flex_debug;
}

void urj_vhdl_set_debug (int  _bdebug , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    yy_flex_debug = _bdebug ;
}

/* Accessor methods for yylval and yylloc */

YYSTYPE * urj_vhdl_get_lval  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    return yylval;
}

void urj_vhdl_set_lval (YYSTYPE *  yylval_param , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    yylval = yylval_param;
}

/* User-visible API */

/* urj_vhdl_lex_init is special because it creates the scanner itself, so it is
 * the ONLY reentrant function that doesn't take the scanner as the last argument.
 * That's why we explicitly handle the declaration, instead of using our macros.
 */

int urj_vhdl_lex_init(yyscan_t* ptr_yy_globals)

{
    if (ptr_yy_globals == NULL){
        errno = EINVAL;
        return 1;
    }

    *ptr_yy_globals = (yyscan_t) urj_vhdl_alloc ( sizeof( struct yyguts_t ), NULL );

    if (*ptr_yy_globals == NULL){
        errno = ENOMEM;
        return 1;
    }

    /* By setting to 0xAA, we expose bugs in yy_init_globals. Leave at 0x00 for releases. */
    memset(*ptr_yy_globals,0x00,sizeof(struct yyguts_t));

    return yy_init_globals ( *ptr_yy_globals );
}

/* urj_vhdl_lex_init_extra has the same functionality as urj_vhdl_lex_init, but follows the
 * convention of taking the scanner as the last argument. Note however, that
 * this is a *pointer* to a scanner, as it will be allocated by this call (and
 * is the reason, too, why this function also must handle its own declaration).
 * The user defined value in the first argument will be available to urj_vhdl_alloc in
 * the yyextra field.
 */

int urj_vhdl_lex_init_extra(YY_EXTRA_TYPE yy_user_defined,yyscan_t* ptr_yy_globals )

{
    struct yyguts_t dummy_yyguts;

    urj_vhdl_set_extra (yy_user_defined, &dummy_yyguts);

    if (ptr_yy_globals == NULL){
        errno = EINVAL;
        return 1;
    }
	
    *ptr_yy_globals = (yyscan_t) urj_vhdl_alloc ( sizeof( struct yyguts_t ), &dummy_yyguts );
	
    if (*ptr_yy_globals == NULL){
        errno = ENOMEM;
        return 1;
    }
    
    /* By setting to 0xAA, we expose bugs in
    yy_init_globals. Leave at 0x00 for releases. */
    memset(*ptr_yy_globals,0x00,sizeof(struct yyguts_t));
    
    urj_vhdl_set_extra (yy_user_defined, *ptr_yy_globals);
    
    return yy_init_globals ( *ptr_yy_globals );
}

static int yy_init_globals (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from urj_vhdl_lex_destroy(), so don't allocate here.
     */

    yyg->yy_buffer_stack = 0;
    yyg->yy_buffer_stack_top = 0;
    yyg->yy_buffer_stack_max = 0;
    yyg->yy_c_buf_p = (char *) 0;
    yyg->yy_init = 0;
    yyg->yy_start = 0;

    yyg->yy_start_stack_ptr = 0;
    yyg->yy_start_stack_depth = 0;
    yyg->yy_start_stack =  NULL;

    yyg->yy_state_buf = 0;
    yyg->yy_state_ptr = 0;
    yyg->yy_full_match = 0;
    yyg->yy_lp = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = (FILE *) 0;
    yyout = (FILE *) 0;
#endif

    /* For future reference: Set errno on error, since we are called by
     * urj_vhdl_lex_init()
     */
    return 0;
}

/* urj_vhdl_lex_destroy is for both reentrant and non-reentrant scanners. */
int urj_vhdl_lex_destroy  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		urj_vhdl__delete_buffer(YY_CURRENT_BUFFER ,yyscanner );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		urj_vhdl_pop_buffer_state(yyscanner);
	}

	/* Destroy the stack itself. */
	urj_vhdl_free(yyg->yy_buffer_stack ,yyscanner);
	yyg->yy_buffer_stack = NULL;

    /* Destroy the start condition stack. */
        urj_vhdl_free(yyg->yy_start_stack ,yyscanner );
        yyg->yy_start_stack = NULL;

    urj_vhdl_free ( yyg->yy_state_buf , yyscanner);
    yyg->yy_state_buf  = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * urj_vhdl_lex() is called, initialization will occur. */
    yy_init_globals( yyscanner);

    /* Destroy the main struct (reentrant only). */
    urj_vhdl_free ( yyscanner , yyscanner );
    yyscanner = NULL;
    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, yyconst char * s2, int n , yyscan_t yyscanner)
{
	struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
	(void)yyg;

	int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * s , yyscan_t yyscanner)
{
	int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *urj_vhdl_alloc (yy_size_t  size , yyscan_t yyscanner)
{
	struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
	(void)yyg;
	return (void *) malloc( size );
}

void *urj_vhdl_realloc  (void * ptr, yy_size_t  size , yyscan_t yyscanner)
{
	struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
	(void)yyg;

	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
}

void urj_vhdl_free (void * ptr , yyscan_t yyscanner)
{
	struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
	(void)yyg;
	free( (char *) ptr );	/* see urj_vhdl_realloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 355 "vhdl_flex.l"



/*****************************************************************************
 * void *urj_vhdl_flex_init( FILE *f, int mode )
 *
 * Initializes the scanner and storage elements extra data structure.
 *
 * Parameters
 *   f         : descriptor of file for scanning
 *   proc_mode : processing mode, consisting of BSDL_MODE_* bits
 *
 * Returns
 *   pointer to newly initialized scanner structure
 ****************************************************************************/
void *
urj_vhdl_flex_init (FILE *f, int proc_mode)
{
    urj_bsdl_scan_extra_t *extra;
    yyscan_t scanner;

    /* get our scanner structure */
    if (urj_vhdl_lex_init (&scanner) != 0)
    {
        urj_bsdl_ftl_set (proc_mode, URJ_ERROR_BSDL_VHDL,
                          "Scanner could not be initialized");
        return NULL;
    }
    urj_vhdl_set_in (f, scanner);

    if (!(extra = malloc (sizeof (urj_bsdl_scan_extra_t))))
    {
        urj_bsdl_ftl_set (proc_mode, URJ_ERROR_OUT_OF_MEMORY,
                          "No memory");
        urj_vhdl_lex_destroy (scanner);
        return NULL;
    }

    extra->proc_mode = proc_mode;
    extra->Compile_Errors = 0;
    extra->Base = DECIMAL;

    urj_vhdl_set_extra (extra, scanner);

    return scanner;
}


/*****************************************************************************
 * void urj_vhdl_flex_deinit( void *scanner )
 *
 * Deinitializes the scanner and closes the input file.
 *
 * Parameters
 *   scanner : pointer to scanner definition structure
 *
 * Returns
 *   void
 ****************************************************************************/
void
urj_vhdl_flex_deinit (void *scanner)
{
    if (urj_vhdl_get_in (scanner))
    {
        /* file might still be open so close it in any case
           e.g. when a compile error occured and the parser didn't hit EOF/urj_vhdl_wrap() */
        fclose (urj_vhdl_get_in (scanner));
        urj_vhdl_set_in (NULL, scanner);
    }
    free (urj_vhdl_get_extra (scanner));
    urj_vhdl_lex_destroy (scanner);
}


/*****************************************************************************
 * void urj_vhdl_wrap(yyscan_t scanner )
 *
 * Closes the input file upon EOF condition.
 *
 * Parameters
 *   scanner : pointer to scanner definition structure
 *
 * Returns
 *   1
 ****************************************************************************/
int
urj_vhdl_wrap (yyscan_t scanner)
{
    if (urj_vhdl_get_in (scanner))
    {
        fclose (urj_vhdl_get_in (scanner));
        urj_vhdl_set_in (NULL, scanner);
    }
    return 1;
}


/*****************************************************************************
 * char *new_string( urj_bsdl_scan_extra_t * extra, const char *str )
 *
 * Allocates memory for a string and copies the contents of *str.
 *
 * Parameters
 *   extra : pointer to extra data structure
 *   str   : pointer to string to be duplicated
 *
 * Returns
 *   pointer to allocated and initialized string memory
 ****************************************************************************/
static char *
new_string (urj_bsdl_scan_extra_t *extra, const char *str)
{
    char *n_str;
    size_t n_str_size;

    n_str_size = strlen (str) + 1;
    if ((n_str = malloc (n_str_size)))
    {
        strncpy (n_str, str, n_str_size - 1);
        n_str[n_str_size - 1] = '\0';   /* set very last element to EOS */
    }
    else
        urj_bsdl_ftl_set (extra->proc_mode, URJ_ERROR_OUT_OF_MEMORY,
                          "No memory");

    return n_str;
}


/*****************************************************************************
 * void urj_vhdl_flex_switch_file( yyscan_t scanner, char *filename )
 *
 * Selects the specified file for further scanning.
 *
 * Parameters
 *   scanner  : pointer to scanner definition structure
 *   filename : name of the new file to be scanned
 *
 * Returns
 *   void
 ****************************************************************************/
void
urj_vhdl_flex_switch_file (yyscan_t scanner, char *filename)
{
    urj_bsdl_scan_extra_t *extra;
    FILE *f;
    char *s;

    /* convert filename to all upper case */
    s = filename;
    while (*s)
    {
        if (islower (*s))
            *s = toupper (*s);
        s++;
    }

    extra = urj_vhdl_get_extra (scanner);

    /* file in current directory has precedence */
    f = fopen (filename, FOPEN_R);
    if (!f)
    {
        const char *db_path = urj_get_data_dir ();
        char *db_file;

        /* @@@@ RFHH handle malloc failure */
        if ((db_file = malloc (strlen (db_path) + 1 +   /* "/"    */
                               4 +      /* "bsdl" */
                               1 +      /* "/"    */
                               strlen (filename) + 1)))
        {
            strcpy (db_file, db_path);
            strcat (db_file, "/");
            strcat (db_file, "bsdl");
            strcat (db_file, "/");
            strcat (db_file, filename);
            f = fopen (db_file, FOPEN_R);

            if (!f)
                urj_bsdl_ftl_set (extra->proc_mode, URJ_ERROR_IO,
                                  "Cannot open file %s or %s", filename,
                                  db_file);
            free (db_file);
            if (!f)
                return;
        }
    }

    urj_vhdl_push_buffer_state (urj_vhdl__create_buffer (f, YY_BUF_SIZE, scanner), scanner);
    urj_vhdl_set_lineno (1, scanner);
}


/*****************************************************************************
 * int urj_vhdl_flex_get_compile_errors( yyscan_t scanner )
 *
 * Retrieves the accumulated number of compile errors encountered so far.
 *
 * Parameters
 *   scanner : pointer to scanner definition structure
 *
 * Returns
 *   number of compile errors
 ****************************************************************************/
int
urj_vhdl_flex_get_compile_errors (yyscan_t scanner)
{
    urj_bsdl_scan_extra_t *extra = urj_vhdl_get_extra (scanner);
    return extra->Compile_Errors;
}


/*****************************************************************************
 * void urj_vhdl_flex_set_compile_errors( int n, yyscan_t scanner )
 *
 * Sets the number of compile errors to n.
 *
 * Parameters
 *   n       : preset number
 *   scanner : pointer to scanner definition structure
 *
 * Returns
 *   void
 ****************************************************************************/
static void
urj_vhdl_flex_set_compile_errors (int n, yyscan_t scanner)
{
    urj_bsdl_scan_extra_t *extra = urj_vhdl_get_extra (scanner);
    extra->Compile_Errors = n;
}


/*****************************************************************************
 * int urj_vhdl_flex_postinc_compile_errors( yyscan_t scanner )
 *
 * Increments the number of compile errors.
 *
 * Parameters
 *   scanner : pointer to scanner definition structure
 *
 * Returns
 *   number of compile errors before increment
 ****************************************************************************/
int
urj_vhdl_flex_postinc_compile_errors (yyscan_t scanner)
{
    int errors = urj_vhdl_flex_get_compile_errors (scanner);

    urj_vhdl_flex_set_compile_errors (errors + 1, scanner);
    return errors;
}


/*****************************************************************************
 * int urj_vhdl_flex_get_lineno( yyscan_t scanner )
 *
 * Returns the current line number in the scanned file.
 *
 * Parameters
 *   scanner : pointer to scanner definition structure
 *
 * Returns
 *   current line number
 ****************************************************************************/
int
urj_vhdl_flex_get_lineno (yyscan_t scanner)
{
    return urj_vhdl_get_lineno (scanner);
}


/*
 Local Variables:
 mode:C
 c-default-style:gnu
 indent-tabs-mode:nil
 End:
*/

